import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    name: "HyperX Cloud II Wireless",
    brand: "HyperX",
    price: "101",
    category: "headphone",
    rating: 4,
    discount: 40,
    src: "/assets/product-img/HyperXII.png",
    newBadge: true,
    featured: true,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Acer Predator X27",
    brand: "Acer",
    price: "200",
    category: "monitor",
    rating: 3,
    discount: 30,
    src: "/assets/product-img/acer-predator-x27.png",
    newBadge: false,
    featured: true,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Acer Predator XB273K",
    brand: "Acer",
    price: "300",
    category: "monitor",
    rating: 3,
    discount: 60,
    src: "/assets/product-img/acer-predator.png",
    newBadge: true,
    featured: true,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "LG UltraGear",
    brand: "LG",
    price: "200",
    category: "monitor",
    rating: 2,
    discount: 60,
    src: "/assets/product-img/lg-ultra.png",
    newBadge: false,
    featured: false,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Razer Thresher",
    brand: "Razer",
    price: "500",
    category: "headphone",
    rating: 1,
    discount: 60,
    src: "/assets/product-img/razer-thresher.png",
    newBadge: false,
    featured: false,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Razer Turret",
    brand: "Razer",
    price: "540",
    category: "keyboard",
    rating: 1,
    discount: 60,
    src: "/assets/product-img/razer-turret.png",
    newBadge: false,
    featured: false,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "SteelSeries Arctis 7",
    brand: "SteelSeries",
    price: "600",
    category: "headphone",
    rating: 5,
    discount: 60,
    src: "/assets/product-img/steel-arctics.png",
    newBadge: false,
    featured: false,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Steelseries Arctis 9X",
    brand: "SteelSeries",
    price: "100",
    category: "headphone",
    rating: 4,
    discount: 60,
    src: "/assets/product-img/steel-arctics9.png",
    newBadge: true,
    featured: true,
    quantity: 1,
  },
  {
    id: uuid(),
    name: "Razer BlackWidow V3 Pro",
    brand: "Razer",
    price: "550",
    category: "keyboard",
    rating: 2,
    discount: 60,
    src: "/assets/product-img/corsair.png",
    newBadge: false,
    featured: false,
    quantity: 1,
  },

];

// export { products }

